window.BJT_GAME_CONFIG = {
  version: '12.3',
  mainTitles: [
    {level:1,name:'言境初醒者',desc:'剛踏入語言世界。'},
    {level:5,name:'語紋學徒',desc:'開始辨識語言規則留下的紋理。'},
    {level:10,name:'語律行者',desc:'能依語言規則穩定前進。'},
    {level:15,name:'真意追蹤者',desc:'開始追蹤字面之外的意圖。'},
    {level:20,name:'語境獵手',desc:'能主動捕捉場面與關係線索。'},
    {level:25,name:'交涉執刃者',desc:'開始用語言處理請求、拒絕與交涉。'},
    {level:30,name:'敬界破譯者',desc:'敬語的方向與邊界逐漸清晰。'},
    {level:35,name:'語脈觀測者',desc:'不只理解句子，也看見資訊流動。'},
    {level:40,name:'真意解析者',desc:'能拆解說話者真正的目的。'},
    {level:45,name:'言界巡狩者',desc:'跨越不同題型與商務場景作戰。'},
    {level:50,name:'語律裁決者',desc:'開始裁定何者才是此刻最適切的言語。'},
    {level:55,name:'境界執行者',desc:'從理解規則進入穩定應用。'},
    {level:60,name:'深層解碼者',desc:'能處理高密度、複雜的商務訊息。'},
    {level:65,name:'言外洞察者',desc:'開始讀懂沒有直接說出口的資訊。'},
    {level:70,name:'萬象解析者',desc:'敬語、情境、聽讀與意圖開始整合。'},
    {level:75,name:'語界裁定者',desc:'能在相近選項間做高階判斷。'},
    {level:80,name:'境界支配者',desc:'主要領域已能穩定掌握。'},
    {level:85,name:'深淵踏破者',desc:'進入最高難度的語用與綜合領域。'},
    {level:90,name:'言界征服者',desc:'主要能力領域已被逐一攻克。'},
    {level:95,name:'終境超越者',desc:'只剩最後一道境界。'},
    {level:99,name:'終極言語使',desc:'最後的門已經出現在眼前。'},
    {level:100,name:'萬語歸一者',desc:'規則、情境與意圖最終匯聚為理解。'}
  ],
  bosses: [
    {id:'M01',moduleId:'M01',name:'偽象裁決者',subtitle:'情境判斷領域',hp:600,baseDamage:40,xp:200,rewardTitle:'boss_m01'},
    {id:'M02',moduleId:'M02',name:'雙面敬語鬼',subtitle:'敬語領域',hp:600,baseDamage:40,xp:200,rewardTitle:'boss_m02'},
    {id:'M03',moduleId:'M03',name:'拒絕吞噬獸',subtitle:'交涉領域',hp:600,baseDamage:40,xp:200,rewardTitle:'boss_m03'},
    {id:'M04',moduleId:'M04',name:'無貌傳令者',subtitle:'電話・接待領域',hp:600,baseDamage:40,xp:200,rewardTitle:'boss_m04'},
    {id:'M05',moduleId:'M05',name:'殘響支配者',subtitle:'聽解領域',hp:600,baseDamage:40,xp:200,rewardTitle:'boss_m05'},
    {id:'M06',moduleId:'M06',name:'千眼情報魔',subtitle:'聽讀解領域',hp:600,baseDamage:40,xp:200,rewardTitle:'boss_m06'},
    {id:'M07',moduleId:'M07',name:'契文迷宮守門人',subtitle:'讀解・商務文書領域',hp:600,baseDamage:40,xp:200,rewardTitle:'boss_m07'},
    {id:'M08',moduleId:'M08',name:'言外深淵王',subtitle:'高階語用領域',hp:600,baseDamage:40,xp:200,rewardTitle:'boss_m08'},
    {id:'FINAL',moduleId:null,name:'無名之境',subtitle:'最終混合領域',hp:1000,baseDamage:45,xp:500,rewardTitle:'boss_final',final:true}
  ],
  specialTitles: [
    {id:'boss_m01',name:'真意識破者',rarity:'BOSS',desc:'擊破「偽象裁決者」。',group:'boss'},
    {id:'boss_m02',name:'敬律斬鬼者',rarity:'BOSS',desc:'擊破「雙面敬語鬼」。',group:'boss'},
    {id:'boss_m03',name:'拒境破刃者',rarity:'BOSS',desc:'擊破「拒絕吞噬獸」。',group:'boss'},
    {id:'boss_m04',name:'萬訊不失者',rarity:'BOSS',desc:'擊破「無貌傳令者」。',group:'boss'},
    {id:'boss_m05',name:'殘響獵手',rarity:'BOSS',desc:'擊破「殘響支配者」。',group:'boss'},
    {id:'boss_m06',name:'千變追蹤者',rarity:'BOSS',desc:'擊破「千眼情報魔」。',group:'boss'},
    {id:'boss_m07',name:'文書破界者',rarity:'BOSS',desc:'擊破「契文迷宮守門人」。',group:'boss'},
    {id:'boss_m08',name:'沉默解讀者',rarity:'BOSS',desc:'擊破「言外深淵王」。',group:'boss'},
    {id:'boss_all',name:'八域征服者',rarity:'LEGEND',desc:'擊破八大領域 Boss。',group:'boss'},
    {id:'boss_final',name:'境界終結者',rarity:'MYTHIC',desc:'擊破最終個體「無名之境」。',group:'boss'},

    {id:'correct_100',name:'百問斬',rarity:'RARE',desc:'累積答對 100 題。',group:'achievement',condition:{type:'correctAnswers',value:100}},
    {id:'correct_1000',name:'千問斬',rarity:'EPIC',desc:'累積答對 1,000 題。',group:'achievement',condition:{type:'correctAnswers',value:1000}},
    {id:'combo_10',name:'十連不斷',rarity:'RARE',desc:'達成 10 Combo。',group:'achievement',condition:{type:'maxCombo',value:10}},
    {id:'combo_25',name:'連鎖獵手',rarity:'RARE',desc:'達成 25 Combo。',group:'achievement',condition:{type:'maxCombo',value:25}},
    {id:'combo_50',name:'五十連境',rarity:'EPIC',desc:'達成 50 Combo。',group:'achievement',condition:{type:'maxCombo',value:50}},
    {id:'combo_75',name:'斷絕失誤者',rarity:'EPIC',desc:'達成 75 Combo。',group:'achievement',condition:{type:'maxCombo',value:75},hidden:true},
    {id:'combo_100',name:'百連無斷',rarity:'LEGEND',desc:'達成 100 Combo。',group:'achievement',condition:{type:'maxCombo',value:100},hidden:true},
    {id:'revenge_25',name:'逆轉者',rarity:'RARE',desc:'讓 25 題曾經答錯的題目完成復仇。',group:'achievement',condition:{type:'revengeUnique',value:25}},
    {id:'revenge_100',name:'逆境吞噬者',rarity:'EPIC',desc:'讓 100 題曾經答錯的題目完成復仇。',group:'achievement',condition:{type:'revengeUnique',value:100}},
    {id:'revenge_250',name:'敗北狩獵者',rarity:'LEGEND',desc:'讓 250 題曾經答錯的題目完成復仇。',group:'achievement',condition:{type:'revengeUnique',value:250},hidden:true},
    {id:'review_25',name:'記憶守望者',rarity:'RARE',desc:'完成 25 次到期複習。',group:'achievement',condition:{type:'reviewSuccesses',value:25}},
    {id:'review_100',name:'深層記憶者',rarity:'EPIC',desc:'完成 100 次到期複習。',group:'achievement',condition:{type:'reviewSuccesses',value:100}},
    {id:'streak_7',name:'不息之火',rarity:'RARE',desc:'連續 7 天完成有效學習。',group:'achievement',condition:{type:'studyStreak',value:7}},
    {id:'streak_30',name:'不熄之火',rarity:'EPIC',desc:'連續 30 天完成有效學習。',group:'achievement',condition:{type:'studyStreak',value:30},hidden:true},
    {id:'all_mastered',name:'萬象皆明',rarity:'LEGEND',desc:'M01～M08 全部課程達到「已掌握」。',group:'achievement',condition:{type:'allMastered',value:1},hidden:true},
    {id:'perfect_50',name:'零誤差領域',rarity:'EPIC',desc:'一輪至少 50 題且 100% 正確。',group:'achievement',condition:{type:'perfect50',value:1},hidden:true},
    {id:'final_completion',name:'界外之人',rarity:'MYTHIC',desc:'Lv.100、全課程掌握、八 Boss 與 Final Boss 全部完成。',group:'achievement',condition:{type:'finalCompletion',value:1},hidden:true}
  ]
};
